config/routes.rb
Rails.application.routes.draw do

resources :users
resources :sessions
resources :difficulties
resources :genres
resources :quizzes


get "/quiz_results", to: "quiz_results#index", as: "quiz_results"
get "/quiz_results/quiz_session", to: "quiz_results#quiz_session", as: "quiz_session"
post "/quiz_results/mark", to: "quiz_results#mark", as: "quiz_mark"
get "/quiz_results/leaderboards", to: "quiz_results#leaderboards", as: "leaderboards"
delete "/sessions", to: "sessions#destroy"

get "/quiz_results/previous_results", to: "quiz_results#previous_results", as: "previous_results"

# get "/quiz_users", to: "quiz_users#index", as: "quiz_users"
# get "/quiz_users/new", to: "quiz_users#new", as: "new_quiz_users"
# get "/quiz_users/:id", to: "quiz_users#show", as: "quiz_user"
# get "/quiz_users", to: "quiz_users#create"

end

app/models/quiz_result.rb
class QuizResult < ApplicationRecord

    validates :genre_id, {presence: true}
    validates :difficulty_id, {presence: true}


belongs_to :user
belongs_to :quiz
belongs_to :difficulty
belongs_to :genre



    def self.top_10
        @record_number1 = self.all.max_by(10) {|qr| qr.answers }.length
        if @record_number1 < 10
            self.all.max_by(@record_number1) {|qr| qr.answers }
        else
            self.all.max_by(10) {|qr| qr.answers }
        end
    end

    def self.bottom_10
        @record_number2 = self.all.min_by(10) {|qr| qr.answers }.length
        if @record_number2 < 10
            self.all.min_by(@record_number2) {|qr| qr.answers }
        else
            self.all.min_by(10) {|qr| qr.answers }
        end
    end

    def self.top_3_by_genre1
        @record_number3 = self.all.where(genre_id: 1).max_by(3) {|qr| qr.answers }.length
        if @record_number3 < 3
            self.all.where(genre_id: 1).max_by(@record_number3) {|qr| qr.answers }
        else
            self.all.where(genre_id: 1).max_by(3) {|qr| qr.answers }
        end
    end

    def self.bottom_3_by_genre1
        @record_number4 = self.all.where(genre_id: 1).min_by(3) {|qr| qr.answers }.length
        if @record_number4 < 3
            self.all.where(genre_id: 1).min_by(@record_number4) {|qr| qr.answers }
        else
            self.all.where(genre_id: 1).min_by(3) {|qr| qr.answers }
        end
    end

    def self.top_3_by_genre2
        @record_number5 = self.all.where(genre_id: 2).max_by(3) {|qr| qr.answers }.length
        if @record_number5 < 3
            self.all.where(genre_id: 2).max_by(@record_number5) {|qr| qr.answers }
        else
            self.all.where(genre_id: 2).max_by(3) {|qr| qr.answers }
        end
    end

    def self.bottom_3_by_genre2
        @record_number6 = self.all.where(genre_id: 2).min_by(3) {|qr| qr.answers }.length
        if @record_number6 < 3
            self.all.where(genre_id: 2).min_by(@record_number6) {|qr| qr.answers }
        else
            self.all.where(genre_id: 2).min_by(3) {|qr| qr.answers }
        end
    end

    def self.top_3_by_genre3
        @record_number7 = self.all.where(genre_id: 3).max_by(3) {|qr| qr.answers }.length
        if @record_number7 < 3
            self.all.where(genre_id: 3).max_by(@record_number7) {|qr| qr.answers }
        else
            self.all.where(genre_id: 3).max_by(3) {|qr| qr.answers }
        end
    end

    def self.bottom_3_by_genre3
        @record_number8 = self.all.where(genre_id: 3).min_by(3) {|qr| qr.answers }.length
        if @record_number8 < 3
            self.all.where(genre_id: 3).min_by(@record_number8) {|qr| qr.answers }
        else
            self.all.where(genre_id: 3).min_by(3) {|qr| qr.answers }
        end
    end

end

app/controllers/quiz_results_controller.rb
class QuizResultsController < ApplicationController
    before_action :authorize_user, only: [:quiz_session, :mark, :previous_results] # Before we let a user access any of these routes, we check if they're logged in
    
    
    
    def index
        

    end

    def quiz_session
        if params[:genre_id] == ""
            redirect_to quiz_results_path
            flash[:notice] = "You need to select a genre and challenge level to start a quiz!"

        elsif params[:difficulty_id] == ""
            redirect_to quiz_results_path
            flash[:notice] = "You need to select a genre and challenge level to start a quiz!"
        else
        @genre_id = params[:genre_id]
        @difficulty_id = params[:difficulty_id]
        @quizzes = Quiz.all.where(genre_id: @genre_id).where(difficulty_id: @difficulty_id)
        @random_quiz_questions = @quizzes.order("RANDOM()").limit(5)
    end
end

    def mark
        
        quizzes = Quiz.find(params[:quizzes])
        
        @correct_answers = []
        @answers = []
        quizzes.each do |q|
            @answers << {quiz: q, right: q.right_answer(params["quiz#{q.id}"])}
           end
            @answers.each do |q|
                if q[:right] == true
                    @correct_answers << q 
                end
            end
        @quiz_answers = QuizResult.create(user_id: session[:user_id], quiz_id: @answers.first[:quiz][:id], difficulty_id: @answers.first[:quiz][:difficulty_id], genre_id: @answers.first[:quiz][:genre_id], answers: @correct_answers.length)
       
    

      
      
    end

    def previous_results

        @my_results = QuizResult.where(user_id: session[:user_id])


    end

    def leaderboards
        @top10 = QuizResult.top_10
        @bottom10 = QuizResult.bottom_10
        @top3_by_genre1 = QuizResult.top_3_by_genre1
        @bottom3_by_genre1 = QuizResult.bottom_3_by_genre1
        @top3_by_genre2 = QuizResult.top_3_by_genre2
        @bottom3_by_genre2 = QuizResult.bottom_3_by_genre2
        @top3_by_genre3 = QuizResult.top_3_by_genre3
        @bottom3_by_genre3 = QuizResult.bottom_3_by_genre3
        @record_number8 = QuizResult.all.where(genre_id: 3).min_by(3) {|qr| qr.answers }.length
        @record_number7 = QuizResult.all.where(genre_id: 3).max_by(3) {|qr| qr.answers }.length
        @record_number6 = QuizResult.all.where(genre_id: 2).min_by(3) {|qr| qr.answers }.length
        @record_number5 = QuizResult.all.where(genre_id: 2).max_by(3) {|qr| qr.answers }.length
        @record_number4 = QuizResult.all.where(genre_id: 1).min_by(3) {|qr| qr.answers }.length
        @record_number3 = QuizResult.all.where(genre_id: 1).max_by(3) {|qr| qr.answers }.length
        @record_number2 = QuizResult.all.min_by(10) {|qr| qr.answers }.length
        @record_number1 = QuizResult.all.max_by(10) {|qr| qr.answers }.length

        @genre_1_name = Genre.find(1).name
        @genre_2_name = Genre.find(2).name
        @genre_3_name = Genre.find(3).name
    
        
    end

    



    private
    
    def quiz_params
        params.require(:quiz).permit(:question, :difficulty_id, :genre_id, :answers, :image_url, :quizzes)
    end

end

app/views/quiz_results/index.html.erb
<div class="stage">
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
  <div class="layer"></div>
</div>

<h3>Please choose your quiz</h3><br>

<%= form_tag({action: :quiz_session}, {method: :get}) do%>

<div class="myclass">
<%= label_tag :genre_id, "Genre:" %><br>
<%= @genre_select = select_tag :genre_id, options_from_collection_for_select(Genre.all, "id", "name", selected: @genre_id), include_blank: "Please Choose Genre" %>
</div><br>
<div class="myclass">
<%= label_tag :difficulty_id, "Challenge level:" %><br>
<%= select_tag :difficulty_id, options_from_collection_for_select(Difficulty.all, "id", "name", selected: @difficulty_id), include_blank: "Please Choose Challnge Level" %>
</div><br>
<% if @genre_select != "Please Choose Genre"%>
<%= submit_tag "Start Quiz!" %><br>
<%end%>

<%=link_to "Previous Results", previous_results_path%><br><br><br>
<%= link_to "Leaderboards", leaderboards_path%>
<% end %>
<br>
<br>

app/views/quiz_results/leaderboards.html.erb
<h1>Leaderboards</h1>




<h3>Top 10</h3>
<% if @record_number1 > 0 %>
<table border="1">
<tr><th>Score</th> <th>Player Name</th> <th>Genre Name</th> <th>Challenge Level</th></tr>
<% @top10.each do |qr| %>
    <tr>
    <td><%= qr.answers %></td>
    <td><%= qr.user.name %></td>
    <td><%= qr.genre.name %></td>
    <td><%= qr.difficulty.name %></td>
    </tr>
    <% end %>
    </table>
<%else%>
<h3>"No record"</h3>
<% end %>
<br>



<h3>Bottom 10</h3>
<% if @record_number2 > 0%>
<table border="1">
<tr><th>Score</th> <th>Player Name</th> <th>Genre Name</th> <th>Challenge Level</th></tr>
<% @bottom10.each do |qr| %>
    <tr>
    <td><%= qr.answers %></td>
    <td><%= qr.user.name %></td>
    <td><%= qr.genre.name %></td>
    <td><%= qr.difficulty.name %></td>
    </tr>
    <% end %>
    </table>
<%else%>
<h3>"No record"</h3>
<% end %>
<br>


<h3>Top 3 by Genre: <%= @genre_1_name %></h3>
<% if @record_number3 > 0%>
<table border="1">
<tr><th>Score</th> <th>Player Name</th> <th>Genre Name</th> <th>Challenge Level</th></tr>
<% @top3_by_genre1.each do |qr| %>
    <tr>
    <td><%= qr.answers %></td>
    <td><%= qr.user.name %></td>
    <td><%= qr.genre.name %></td>
    <td><%= qr.difficulty.name %></td>
    </tr>
    <% end %>
    </table>
<%else%>
<h3>"No record"</h3>
<% end %>
<br>


<h3>Bottom 3 by Genre: <%= @genre_1_name %></h3>
<% if @record_number4 > 0 %>
<table border="1">
<tr><th>Score</th> <th>Player Name</th> <th>Genre Name</th> <th>Challenge Level</th></tr>
<% @bottom3_by_genre1.each do |qr| %>
    <tr>
    <td><%= qr.answers %></td>
    <td><%= qr.user.name %></td>
    <td><%= qr.genre.name %></td>
    <td><%= qr.difficulty.name %></td>
    </tr>
    <% end %>
    </table>
<%else%>
<h3>"No record"</h3>
<% end %>
<br>


<h3>Top 3 by Genre: <%= @genre_2_name %></h3>
<% if @record_number5 > 0%>
<table border="1">
<tr><th>Score</th> <th>Player Name</th> <th>Genre Name</th> <th>Challenge Level</th></tr>
<% @top3_by_genre2.each do |qr| %>
    <tr>
    <td><%= qr.answers %></td>
    <td><%= qr.user.name %></td>
    <td><%= qr.genre.name %></td>
    <td><%= qr.difficulty.name %></td>
    </tr>
    <% end %>
    </table>
<%else%>
<h3>"No record"</h3>
<% end %>
<br>


<h3>Bottom 3 by Genre: <%= @genre_2_name %></h3>
<% if @record_number6 >0 %>
<table border="1">
<tr><th>Score</th> <th>Player Name</th> <th>Genre Name</th> <th>Challenge Level</th></tr>
<% @bottom3_by_genre2.each do |qr| %>
    <tr>
    <td><%= qr.answers %></td>
    <td><%= qr.user.name %></td>
    <td><%= qr.genre.name %></td>
    <td><%= qr.difficulty.name %></td>
    </tr>
    <% end %>
    </table>
<%else%>
<h3>"No record"</h3>
<% end %>
<br>


<h3>Top 3 by Genre: <%= @genre_3_name %></h3>
<% if @record_number7 > 0%>
<table border="1">
<tr><th>Score</th> <th>Player Name</th> <th>Genre Name</th> <th>Challenge Level</th></tr>
<% @top3_by_genre3.each do |qr| %>
    <tr>
    <td><%= qr.answers %></td>
    <td><%= qr.user.name %></td>
    <td><%= qr.genre.name %></td>
    <td><%= qr.difficulty.name %></td>
    </tr>
    <% end %>
    </table>
<%else%>
<h3>"No record"</h3>
<% end %>
<br>


<h3>Bottom 3 by Genre: <%= @genre_3_name %></h3>
<% if @record_number8 > 0 %>
<table border="1">
<tr><th>Score</th> <th>Player Name</th> <th>Genre Name</th> <th>Challenge Level</th></tr>
<% @bottom3_by_genre3.each do |qr| %>
    <tr>
    <td><%= qr.answers %></td>
    <td><%= qr.user.name %></td>
    <td><%= qr.genre.name %></td>
    <td><%= qr.difficulty.name %></td>
    </tr>
    <% end %>
    </table>
<%else%>
<h3>"No record"</h3>
<% end %>
<br>
<%= link_to "Back to Home Page", quiz_results_path%>

app/views/quiz_results/mark.html.erb
<div class="container text-center">
<h1>Quiz Results</h1>
<%= form_tag quiz_results_path do%>

<% @answers.each do |answer|%>

<p> Question: <%= answer[:quiz].question %></p>
<p> You got this question <%= answer[:right]? "Correct Answer!" : "Wrong!!" %></p><br>
<% end %>

<%end%>
<br><%= link_to "Save Results", quiz_results_path%>
</div>

app/views/quiz_results/previous_results.html.erb
<h1>Your Previous Results</h1>

<% @my_results.each do |q|%>
<h3>Difficulty:</h3>
<%= q.difficulty.name%><br>
<h3>Genre:</h3>
<%= q.genre.name%><br>
<h3>Correct Answers:</h3>
<%= q.answers %><br><br><br>
<%end%>

<br><%= link_to "Back to Home Page", quiz_results_path%>

app/views/quiz_results/quiz_session.html.erb
    <div class ="container text-center">
    <h1>Your Quiz</h1>

    <%= form_tag quiz_mark_path, html: { autocomplete: "off" } do %>

    <% @random_quiz_questions.each do |quiz| %>
    <p><%= quiz.question %></p><br>
    <p><%= image_tag(quiz.image_url) %></p><br>
    <%= hidden_field_tag "quizzes[]", quiz.id %>
    <label>Your Answer: <%= text_field_tag "quiz#{quiz.id}" %></label><br><br>
    
    <% end %>
    <%= submit_tag "Submit Your Answers"%>
    <% end %>
    </div>